# Main class used by client programs

# require File.expand_path('lib/postal/lmapi/lmapi.rb')
# require File.expand_path('lib/postal/lmapi/lmapiMappingRegistry.rb')
gem 'soap4r'
require 'soap/rpc/driver'

module Postal
  module Lmapi
    class Soap < ::SOAP::RPC::Driver
      DefaultEndpointUrl = "http://mail.active.com:82/"
      NsLmapi = "http://www.lyris.com/lmapi"

      Methods = [
        [ XSD::QName.new(NsLmapi, "ApiVersion"),
          "",
          "apiVersion",
          [ ["retval", "return", ["::SOAP::SOAPString"]] ],
          { :request_style =>  :rpc, :request_use =>  :encoded,
            :response_style => :rpc, :response_use => :encoded,
            :faults => {} }
        ],
        [ XSD::QName.new(NsLmapi, "CurrentUserEmailAddress"),
          "",
          "currentUserEmailAddress",
          [ ["retval", "return", ["::SOAP::SOAPString"]] ],
          { :request_style =>  :rpc, :request_use =>  :encoded,
            :response_style => :rpc, :response_use => :encoded,
            :faults => {} }
        ],
        [ XSD::QName.new(NsLmapi, "DeleteMembers"),
          "",
          "deleteMembers",
          [ ["in", "FilterCriteriaArray", ["Postal::Lmapi::ArrayOfstring", "http://www.lyris.com/lmapi", "Postal::Lmapi::ArrayOfstring"]],
            ["retval", "return", ["::SOAP::SOAPInt"]] ],
          { :request_style =>  :rpc, :request_use =>  :encoded,
            :response_style => :rpc, :response_use => :encoded,
            :faults => {} }
        ],
        [ XSD::QName.new(NsLmapi, "GetMemberID"),
          "",
          "getMemberID",
          [ ["in", "SimpleMemberStructIn", ["Postal::Lmapi::SimpleMemberStruct", "http://tempuri.org/ns1.xsd", "Postal::Lmapi::SimpleMemberStruct"]],
            ["retval", "return", ["::SOAP::SOAPInt"]] ],
          { :request_style =>  :rpc, :request_use =>  :encoded,
            :response_style => :rpc, :response_use => :encoded,
            :faults => {} }
        ],
        [ XSD::QName.new(NsLmapi, "CreateSingleMember"),
          "",
          "createSingleMember",
          [ ["in", "EmailAddress", ["::SOAP::SOAPString"]],
            ["in", "FullName", ["::SOAP::SOAPString"]],
            ["in", "ListName", ["::SOAP::SOAPString"]],
            ["retval", "return", ["::SOAP::SOAPInt"]] ],
          { :request_style =>  :rpc, :request_use =>  :encoded,
            :response_style => :rpc, :response_use => :encoded,
            :faults => {} }
        ],
        [ XSD::QName.new(NsLmapi, "CreateManyMembers"),
          "",
          "createManyMembers",
          [ ["in", "Postal::Lmapi::ArrayOfTinyMemberStructIn", ["Postal::Lmapi::ArrayOfTinyMemberStruct", "http://www.lyris.com/lmapi", "Postal::Lmapi::ArrayOfTinyMemberStruct"]],
            ["in", "ListName", ["::SOAP::SOAPString"]],
            ["in", "SkipBadRecords", ["::SOAP::SOAPBoolean"]],
            ["retval", "return", ["::SOAP::SOAPInt"]] ],
          { :request_style =>  :rpc, :request_use =>  :encoded,
            :response_style => :rpc, :response_use => :encoded,
            :faults => {} }
        ],
        [ XSD::QName.new(NsLmapi, "SqlSelect"),
          "",
          "sqlSelect",
          [ ["in", "SqlStatement", ["::SOAP::SOAPString"]],
            ["retval", "return", ["Postal::Lmapi::ArrayOfArrayOfstring", "http://www.lyris.com/lmapi", "Postal::Lmapi::ArrayOfArrayOfstring"]] ],
          { :request_style =>  :rpc, :request_use =>  :encoded,
            :response_style => :rpc, :response_use => :encoded,
            :faults => {} }
        ],
        [ XSD::QName.new(NsLmapi, "SqlInsert"),
          "",
          "sqlInsert",
          [ ["in", "SqlStatement", ["::SOAP::SOAPString"]],
            ["in", "DataArray", ["Postal::Lmapi::ArrayOfKeyValueType", "http://www.lyris.com/lmapi", "Postal::Lmapi::ArrayOfKeyValueType"]],
            ["in", "ReturnID", ["::SOAP::SOAPBoolean"]],
            ["retval", "return", ["::SOAP::SOAPInt"]] ],
          { :request_style =>  :rpc, :request_use =>  :encoded,
            :response_style => :rpc, :response_use => :encoded,
            :faults => {} }
        ],
        [ XSD::QName.new(NsLmapi, "SqlUpdate"),
          "",
          "sqlUpdate",
          [ ["in", "SqlStatement", ["::SOAP::SOAPString"]],
            ["in", "DataArray", ["Postal::Lmapi::ArrayOfKeyValueType", "http://www.lyris.com/lmapi", "Postal::Lmapi::ArrayOfKeyValueType"]],
            ["in", "SqlWhere", ["::SOAP::SOAPString"]],
            ["retval", "return", ["::SOAP::SOAPBoolean"]] ],
          { :request_style =>  :rpc, :request_use =>  :encoded,
            :response_style => :rpc, :response_use => :encoded,
            :faults => {} }
        ],
        [ XSD::QName.new(NsLmapi, "SqlDelete"),
          "",
          "sqlDelete",
          [ ["in", "TableName", ["::SOAP::SOAPString"]],
            ["in", "SqlWhere", ["::SOAP::SOAPString"]],
            ["retval", "return", ["::SOAP::SOAPBoolean"]] ],
          { :request_style =>  :rpc, :request_use =>  :encoded,
            :response_style => :rpc, :response_use => :encoded,
            :faults => {} }
        ],
        [ XSD::QName.new(NsLmapi, "UpdateMemberPassword"),
          "",
          "updateMemberPassword",
          [ ["in", "SimpleMemberStructIn", ["Postal::Lmapi::SimpleMemberStruct", "http://tempuri.org/ns1.xsd", "Postal::Lmapi::SimpleMemberStruct"]],
            ["in", "Password", ["::SOAP::SOAPString"]],
            ["retval", "return", ["::SOAP::SOAPBoolean"]] ],
          { :request_style =>  :rpc, :request_use =>  :encoded,
            :response_style => :rpc, :response_use => :encoded,
            :faults => {} }
        ],
        [ XSD::QName.new(NsLmapi, "CheckMemberPassword"),
          "",
          "checkMemberPassword",
          [ ["in", "SimpleMemberStructIn", ["Postal::Lmapi::SimpleMemberStruct", "http://tempuri.org/ns1.xsd", "Postal::Lmapi::SimpleMemberStruct"]],
            ["in", "Password", ["::SOAP::SOAPString"]],
            ["retval", "return", ["::SOAP::SOAPBoolean"]] ],
          { :request_style =>  :rpc, :request_use =>  :encoded,
            :response_style => :rpc, :response_use => :encoded,
            :faults => {} }
        ],
        [ XSD::QName.new(NsLmapi, "CopyMember"),
          "",
          "copyMember",
          [ ["in", "SimpleMemberStructIn", ["Postal::Lmapi::SimpleMemberStruct", "http://tempuri.org/ns1.xsd", "Postal::Lmapi::SimpleMemberStruct"]],
            ["in", "EmailAddress", ["::SOAP::SOAPString"]],
            ["in", "FullName", ["::SOAP::SOAPString"]],
            ["in", "ListName", ["::SOAP::SOAPString"]],
            ["retval", "return", ["::SOAP::SOAPInt"]] ],
          { :request_style =>  :rpc, :request_use =>  :encoded,
            :response_style => :rpc, :response_use => :encoded,
            :faults => {} }
        ],
        [ XSD::QName.new(NsLmapi, "CreateList"),
          "",
          "createList",
          [ ["in", "ListTypeEnumIn", [nil, "http://tempuri.org/ns1.xsd", "ListTypeEnum"]],
            ["in", "ListName", ["::SOAP::SOAPString"]],
            ["in", "ShortDescription", ["::SOAP::SOAPString"]],
            ["in", "AdminName", ["::SOAP::SOAPString"]],
            ["in", "AdminEmail", ["::SOAP::SOAPString"]],
            ["in", "AdminPassword", ["::SOAP::SOAPString"]],
            ["in", "Topic", ["::SOAP::SOAPString"]],
            ["retval", "return", ["::SOAP::SOAPInt"]] ],
          { :request_style =>  :rpc, :request_use =>  :encoded,
            :response_style => :rpc, :response_use => :encoded,
            :faults => {} }
        ],
        [ XSD::QName.new(NsLmapi, "DeleteList"),
          "",
          "deleteList",
          [ ["in", "ListName", ["::SOAP::SOAPString"]],
            ["retval", "return", ["::SOAP::SOAPBoolean"]] ],
          { :request_style =>  :rpc, :request_use =>  :encoded,
            :response_style => :rpc, :response_use => :encoded,
            :faults => {} }
        ],
        [ XSD::QName.new(NsLmapi, "EmailOnWhatLists"),
          "",
          "emailOnWhatLists",
          [ ["in", "EmailAddress", ["::SOAP::SOAPString"]],
            ["retval", "return", ["Postal::Lmapi::ArrayOfstring", "http://www.lyris.com/lmapi", "Postal::Lmapi::ArrayOfstring"]] ],
          { :request_style =>  :rpc, :request_use =>  :encoded,
            :response_style => :rpc, :response_use => :encoded,
            :faults => {} }
        ],
        [ XSD::QName.new(NsLmapi, "EmailPasswordOnWhatLists"),
          "",
          "emailPasswordOnWhatLists",
          [ ["in", "EmailAddress", ["::SOAP::SOAPString"]],
            ["in", "Password", ["::SOAP::SOAPString"]],
            ["retval", "return", ["Postal::Lmapi::ArrayOfstring", "http://www.lyris.com/lmapi", "Postal::Lmapi::ArrayOfstring"]] ],
          { :request_style =>  :rpc, :request_use =>  :encoded,
            :response_style => :rpc, :response_use => :encoded,
            :faults => {} }
        ],
        [ XSD::QName.new(NsLmapi, "CreateListAdmin"),
          "",
          "createListAdmin",
          [ ["in", "AdminEmail", ["::SOAP::SOAPString"]],
            ["in", "AdminPassword", ["::SOAP::SOAPString"]],
            ["in", "AdminListName", ["::SOAP::SOAPString"]],
            ["in", "AdminFullName", ["::SOAP::SOAPString"]],
            ["in", "ReceiveListAdminMail", ["::SOAP::SOAPBoolean"]],
            ["in", "ReceiveModerationNotification", ["::SOAP::SOAPBoolean"]],
            ["in", "BypassListModeration", ["::SOAP::SOAPBoolean"]],
            ["retval", "return", ["::SOAP::SOAPInt"]] ],
          { :request_style =>  :rpc, :request_use =>  :encoded,
            :response_style => :rpc, :response_use => :encoded,
            :faults => {} }
        ],
        [ XSD::QName.new(NsLmapi, "CreateMemberBan"),
          "",
          "createMemberBan",
          [ ["in", "MemberBanStructIn", ["Postal::Lmapi::MemberBanStruct", "http://tempuri.org/ns1.xsd", "Postal::Lmapi::MemberBanStruct"]],
            ["retval", "return", ["::SOAP::SOAPInt"]] ],
          { :request_style =>  :rpc, :request_use =>  :encoded,
            :response_style => :rpc, :response_use => :encoded,
            :faults => {} }
        ],
        [ XSD::QName.new(NsLmapi, "GetEmailFromMemberID"),
          "",
          "getEmailFromMemberID",
          [ ["in", "MemberID", ["::SOAP::SOAPInt"]],
            ["retval", "return", ["::SOAP::SOAPString"]] ],
          { :request_style =>  :rpc, :request_use =>  :encoded,
            :response_style => :rpc, :response_use => :encoded,
            :faults => {} }
        ],
        [ XSD::QName.new(NsLmapi, "GetListID"),
          "",
          "getListID",
          [ ["in", "ListName", ["::SOAP::SOAPString"]],
            ["retval", "return", ["::SOAP::SOAPInt"]] ],
          { :request_style =>  :rpc, :request_use =>  :encoded,
            :response_style => :rpc, :response_use => :encoded,
            :faults => {} }
        ],
        [ XSD::QName.new(NsLmapi, "GetListnameFromMemberID"),
          "",
          "getListnameFromMemberID",
          [ ["in", "MemberID", ["::SOAP::SOAPInt"]],
            ["retval", "return", ["::SOAP::SOAPString"]] ],
          { :request_style =>  :rpc, :request_use =>  :encoded,
            :response_style => :rpc, :response_use => :encoded,
            :faults => {} }
        ],
        [ XSD::QName.new(NsLmapi, "ImportContent"),
          "",
          "importContent",
          [ ["in", "ContentID", ["::SOAP::SOAPInt"]],
            ["retval", "return", ["Postal::Lmapi::SimpleMailingStruct", "http://tempuri.org/ns1.xsd", "Postal::Lmapi::SimpleMailingStruct"]] ],
          { :request_style =>  :rpc, :request_use =>  :encoded,
            :response_style => :rpc, :response_use => :encoded,
            :faults => {} }
        ],
        [ XSD::QName.new(NsLmapi, "SelectMembers"),
          "",
          "selectMembers",
          [ ["in", "FilterCriteriaArray", ["Postal::Lmapi::ArrayOfstring", "http://www.lyris.com/lmapi", "Postal::Lmapi::ArrayOfstring"]],
            ["retval", "return", ["Postal::Lmapi::ArrayOfMemberStruct", "http://www.lyris.com/lmapi", "Postal::Lmapi::ArrayOfMemberStruct"]] ],
          { :request_style =>  :rpc, :request_use =>  :encoded,
            :response_style => :rpc, :response_use => :encoded,
            :faults => {} }
        ],
        [ XSD::QName.new(NsLmapi, "SelectSimpleMembers"),
          "",
          "selectSimpleMembers",
          [ ["in", "FilterCriteriaArray", ["Postal::Lmapi::ArrayOfstring", "http://www.lyris.com/lmapi", "Postal::Lmapi::ArrayOfstring"]],
            ["retval", "return", ["Postal::Lmapi::ArrayOfSimpleMemberStruct", "http://www.lyris.com/lmapi", "Postal::Lmapi::ArrayOfSimpleMemberStruct"]] ],
          { :request_style =>  :rpc, :request_use =>  :encoded,
            :response_style => :rpc, :response_use => :encoded,
            :faults => {} }
        ],
        [ XSD::QName.new(NsLmapi, "SendMailing"),
          "",
          "sendMailing",
          [ ["in", "SegmentID", ["::SOAP::SOAPInt"]],
            ["in", "MailingStructIn", ["Postal::Lmapi::MailingStruct", "http://tempuri.org/ns1.xsd", "Postal::Lmapi::MailingStruct"]],
            ["retval", "return", ["::SOAP::SOAPInt"]] ],
          { :request_style =>  :rpc, :request_use =>  :encoded,
            :response_style => :rpc, :response_use => :encoded,
            :faults => {} }
        ],
        [ XSD::QName.new(NsLmapi, "MailingStatus"),
          "",
          "mailingStatus",
          [ ["in", "MailingID", ["::SOAP::SOAPInt"]],
            ["retval", "return", ["::SOAP::SOAPString"]] ],
          { :request_style =>  :rpc, :request_use =>  :encoded,
            :response_style => :rpc, :response_use => :encoded,
            :faults => {} }
        ],
        [ XSD::QName.new(NsLmapi, "ScheduleMailing"),
          "",
          "scheduleMailing",
          [ ["in", "SegmentID", ["::SOAP::SOAPInt"]],
            ["in", "SendDate", ["::SOAP::SOAPDateTime"]],
            ["in", "MailingStructIn", ["Postal::Lmapi::MailingStruct", "http://tempuri.org/ns1.xsd", "Postal::Lmapi::MailingStruct"]],
            ["retval", "return", ["::SOAP::SOAPInt"]] ],
          { :request_style =>  :rpc, :request_use =>  :encoded,
            :response_style => :rpc, :response_use => :encoded,
            :faults => {} }
        ],
        [ XSD::QName.new(NsLmapi, "ModerateMailing"),
          "",
          "moderateMailing",
          [ ["in", "ModerateID", ["::SOAP::SOAPInt"]],
            ["in", "Accept", ["::SOAP::SOAPBoolean"]],
            ["in", "SendRejectMessage", ["::SOAP::SOAPBoolean"]],
            ["retval", "return", ["::SOAP::SOAPBoolean"]] ],
          { :request_style =>  :rpc, :request_use =>  :encoded,
            :response_style => :rpc, :response_use => :encoded,
            :faults => {} }
        ],
        [ XSD::QName.new(NsLmapi, "SelectContent"),
          "",
          "selectContent",
          [ ["in", "FilterCriteriaArray", ["Postal::Lmapi::ArrayOfstring", "http://www.lyris.com/lmapi", "Postal::Lmapi::ArrayOfstring"]],
            ["retval", "return", ["Postal::Lmapi::ArrayOfContentStruct", "http://www.lyris.com/lmapi", "Postal::Lmapi::ArrayOfContentStruct"]] ],
          { :request_style =>  :rpc, :request_use =>  :encoded,
            :response_style => :rpc, :response_use => :encoded,
            :faults => {} }
        ],
        [ XSD::QName.new(NsLmapi, "SelectLists"),
          "",
          "selectLists",
          [ ["in", "ListName", ["::SOAP::SOAPString"]],
            ["in", "SiteName", ["::SOAP::SOAPString"]],
            ["retval", "return", ["Postal::Lmapi::ArrayOfListStruct", "http://www.lyris.com/lmapi", "Postal::Lmapi::ArrayOfListStruct"]] ],
          { :request_style =>  :rpc, :request_use =>  :encoded,
            :response_style => :rpc, :response_use => :encoded,
            :faults => {} }
        ],
        [ XSD::QName.new(NsLmapi, "SelectSegments"),
          "",
          "selectSegments",
          [ ["in", "FilterCriteriaArray", ["Postal::Lmapi::ArrayOfstring", "http://www.lyris.com/lmapi", "Postal::Lmapi::ArrayOfstring"]],
            ["retval", "return", ["Postal::Lmapi::ArrayOfSegmentStruct", "http://www.lyris.com/lmapi", "Postal::Lmapi::ArrayOfSegmentStruct"]] ],
          { :request_style =>  :rpc, :request_use =>  :encoded,
            :response_style => :rpc, :response_use => :encoded,
            :faults => {} }
        ],
        [ XSD::QName.new(NsLmapi, "SendMailingDirect"),
          "",
          "sendMailingDirect",
          [ ["in", "EmailAddressArray", ["Postal::Lmapi::ArrayOfstring", "http://www.lyris.com/lmapi", "Postal::Lmapi::ArrayOfstring"]],
            ["in", "MemberIDArray", ["Postal::Lmapi::ArrayOfint", "http://www.lyris.com/lmapi", "Postal::Lmapi::ArrayOfint"]],
            ["in", "MailingStructIn", ["Postal::Lmapi::MailingStruct", "http://tempuri.org/ns1.xsd", "Postal::Lmapi::MailingStruct"]],
            ["retval", "return", ["::SOAP::SOAPInt"]] ],
          { :request_style =>  :rpc, :request_use =>  :encoded,
            :response_style => :rpc, :response_use => :encoded,
            :faults => {} }
        ],
        [ XSD::QName.new(NsLmapi, "SendMemberDoc"),
          "",
          "sendMemberDoc",
          [ ["in", "SimpleMemberStructIn", ["Postal::Lmapi::SimpleMemberStruct", "http://tempuri.org/ns1.xsd", "Postal::Lmapi::SimpleMemberStruct"]],
            ["in", "DocTypeIn", [nil, "http://tempuri.org/ns1.xsd", "Postal::Lmapi::MessageTypeEnum"]],
            ["retval", "return", ["::SOAP::SOAPInt"]] ],
          { :request_style =>  :rpc, :request_use =>  :encoded,
            :response_style => :rpc, :response_use => :encoded,
            :faults => {} }
        ],
        [ XSD::QName.new(NsLmapi, "TrackingSummary"),
          "",
          "trackingSummary",
          [ ["in", "OutMailID", ["::SOAP::SOAPInt"]],
            ["retval", "return", ["Postal::Lmapi::TrackingSummaryStruct", "http://tempuri.org/ns1.xsd", "Postal::Lmapi::TrackingSummaryStruct"]] ],
          { :request_style =>  :rpc, :request_use =>  :encoded,
            :response_style => :rpc, :response_use => :encoded,
            :faults => {} }
        ],
        [ XSD::QName.new(NsLmapi, "Unsubscribe"),
          "",
          "unsubscribe",
          [ ["in", "SimpleMemberStructArrayIn", ["Postal::Lmapi::ArrayOfSimpleMemberStruct", "http://www.lyris.com/lmapi", "Postal::Lmapi::ArrayOfSimpleMemberStruct"]],
            ["retval", "return", ["::SOAP::SOAPInt"]] ],
          { :request_style =>  :rpc, :request_use =>  :encoded,
            :response_style => :rpc, :response_use => :encoded,
            :faults => {} }
        ],
        [ XSD::QName.new(NsLmapi, "UpdateMemberEmail"),
          "",
          "updateMemberEmail",
          [ ["in", "SimpleMemberStructIn", ["Postal::Lmapi::SimpleMemberStruct", "http://tempuri.org/ns1.xsd", "Postal::Lmapi::SimpleMemberStruct"]],
            ["in", "EmailAddress", ["::SOAP::SOAPString"]],
            ["retval", "return", ["::SOAP::SOAPBoolean"]] ],
          { :request_style =>  :rpc, :request_use =>  :encoded,
            :response_style => :rpc, :response_use => :encoded,
            :faults => {} }
        ],
        [ XSD::QName.new(NsLmapi, "UpdateMemberKind"),
          "",
          "updateMemberKind",
          [ ["in", "SimpleMemberStructIn", ["Postal::Lmapi::SimpleMemberStruct", "http://tempuri.org/ns1.xsd", "Postal::Lmapi::SimpleMemberStruct"]],
            ["in", "MemberKind", [nil, "http://tempuri.org/ns1.xsd", "Postal::Lmapi::MemberKindEnum"]],
            ["retval", "return", ["::SOAP::SOAPBoolean"]] ],
          { :request_style =>  :rpc, :request_use =>  :encoded,
            :response_style => :rpc, :response_use => :encoded,
            :faults => {} }
        ],
        [ XSD::QName.new(NsLmapi, "UpdateMemberStatus"),
          "",
          "updateMemberStatus",
          [ ["in", "SimpleMemberStructIn", ["Postal::Lmapi::SimpleMemberStruct", "http://tempuri.org/ns1.xsd", "Postal::Lmapi::SimpleMemberStruct"]],
            ["in", "MemberStatus", [nil, "http://tempuri.org/ns1.xsd", "Postal::Lmapi::MemberStatusEnum"]],
            ["retval", "return", ["::SOAP::SOAPBoolean"]] ],
          { :request_style =>  :rpc, :request_use =>  :encoded,
            :response_style => :rpc, :response_use => :encoded,
            :faults => {} }
        ],
        [ XSD::QName.new(NsLmapi, "UpdateList"),
          "",
          "updateList",
          [ ["in", "ListStructIn", ["Postal::Lmapi::ListStruct", "http://tempuri.org/ns1.xsd", "Postal::Lmapi::ListStruct"]],
            ["retval", "return", ["::SOAP::SOAPBoolean"]] ],
          { :request_style =>  :rpc, :request_use =>  :encoded,
            :response_style => :rpc, :response_use => :encoded,
            :faults => {} }
        ],
        [ XSD::QName.new(NsLmapi, "UpdateListAdmin"),
          "",
          "updateListAdmin",
          [ ["in", "SimpleMemberStructIn", ["Postal::Lmapi::SimpleMemberStruct", "http://tempuri.org/ns1.xsd", "Postal::Lmapi::SimpleMemberStruct"]],
            ["in", "IsListAdmin", ["::SOAP::SOAPBoolean"]],
            ["in", "ReceiveListAdminMail", ["::SOAP::SOAPBoolean"]],
            ["in", "ReceiveModerationNotification", ["::SOAP::SOAPBoolean"]],
            ["in", "BypassListModeration", ["::SOAP::SOAPBoolean"]],
            ["retval", "return", ["::SOAP::SOAPBoolean"]] ],
          { :request_style =>  :rpc, :request_use =>  :encoded,
            :response_style => :rpc, :response_use => :encoded,
            :faults => {} }
        ],
        [ XSD::QName.new(NsLmapi, "UpdateMemberDemographics"),
          "",
          "updateMemberDemographics",
          [ ["in", "SimpleMemberStructIn", ["Postal::Lmapi::SimpleMemberStruct", "http://tempuri.org/ns1.xsd", "Postal::Lmapi::SimpleMemberStruct"]],
            ["in", "DemographicsArray", ["Postal::Lmapi::ArrayOfKeyValueType", "http://www.lyris.com/lmapi", "Postal::Lmapi::ArrayOfKeyValueType"]],
            ["retval", "return", ["::SOAP::SOAPBoolean"]] ],
          { :request_style =>  :rpc, :request_use =>  :encoded,
            :response_style => :rpc, :response_use => :encoded,
            :faults => {} }
        ],
        [ XSD::QName.new(NsLmapi, "CreateMemberColumn"),
          "",
          "createMemberColumn",
          [ ["in", "FieldName", ["::SOAP::SOAPString"]],
            ["in", "FieldType", [nil, "http://tempuri.org/ns1.xsd", "Postal::Lmapi::FieldTypeEnum"]],
            ["retval", "return", ["::SOAP::SOAPBoolean"]] ],
          { :request_style =>  :rpc, :request_use =>  :encoded,
            :response_style => :rpc, :response_use => :encoded,
            :faults => {} }
        ],
        [ XSD::QName.new(NsLmapi, "DeleteMemberColumn"),
          "",
          "deleteMemberColumn",
          [ ["in", "FieldName", ["::SOAP::SOAPString"]],
            ["retval", "return", ["::SOAP::SOAPBoolean"]] ],
          { :request_style =>  :rpc, :request_use =>  :encoded,
            :response_style => :rpc, :response_use => :encoded,
            :faults => {} }
        ],
        [ XSD::QName.new(NsLmapi, "CreateSegment"),
          "",
          "createSegment",
          [ ["in", "SegmentStructIn", ["Postal::Lmapi::SegmentStruct", "http://tempuri.org/ns1.xsd", "Postal::Lmapi::SegmentStruct"]],
            ["retval", "return", ["::SOAP::SOAPInt"]] ],
          { :request_style =>  :rpc, :request_use =>  :encoded,
            :response_style => :rpc, :response_use => :encoded,
            :faults => {} }
        ],
        [ XSD::QName.new(NsLmapi, "UpdateSegment"),
          "",
          "updateSegment",
          [ ["in", "SegmentStructIn", ["Postal::Lmapi::SegmentStruct", "http://tempuri.org/ns1.xsd", "Postal::Lmapi::SegmentStruct"]],
            ["retval", "return", ["::SOAP::SOAPBoolean"]] ],
          { :request_style =>  :rpc, :request_use =>  :encoded,
            :response_style => :rpc, :response_use => :encoded,
            :faults => {} }
        ],
        [ XSD::QName.new(NsLmapi, "DeleteSegment"),
          "",
          "deleteSegment",
          [ ["in", "SegmentID", ["::SOAP::SOAPInt"]],
            ["retval", "return", ["::SOAP::SOAPBoolean"]] ],
          { :request_style =>  :rpc, :request_use =>  :encoded,
            :response_style => :rpc, :response_use => :encoded,
            :faults => {} }
        ],
        [ XSD::QName.new(NsLmapi, "SendMessage"),
          "",
          "sendMessage",
          [ ["in", "MessageStructIn", ["Postal::Lmapi::MessageStruct", "http://tempuri.org/ns1.xsd", "Postal::Lmapi::MessageStruct"]],
            ["retval", "return", ["::SOAP::SOAPInt"]] ],
          { :request_style =>  :rpc, :request_use =>  :encoded,
            :response_style => :rpc, :response_use => :encoded,
            :faults => {} }
        ],
        [ XSD::QName.new(NsLmapi, "CreateSite"),
          "",
          "createSite",
          [ ["in", "SiteStructIn", ["Postal::Lmapi::SiteStruct", "http://tempuri.org/ns1.xsd", "Postal::Lmapi::SiteStruct"]],
            ["retval", "return", ["::SOAP::SOAPInt"]] ],
          { :request_style =>  :rpc, :request_use =>  :encoded,
            :response_style => :rpc, :response_use => :encoded,
            :faults => {} }
        ],
        [ XSD::QName.new(NsLmapi, "UpdateSite"),
          "",
          "updateSite",
          [ ["in", "SiteStructIn", ["Postal::Lmapi::SiteStruct", "http://tempuri.org/ns1.xsd", "Postal::Lmapi::SiteStruct"]],
            ["retval", "return", ["::SOAP::SOAPBoolean"]] ],
          { :request_style =>  :rpc, :request_use =>  :encoded,
            :response_style => :rpc, :response_use => :encoded,
            :faults => {} }
        ],
        [ XSD::QName.new(NsLmapi, "DeleteSite"),
          "",
          "deleteSite",
          [ ["in", "SiteID", ["::SOAP::SOAPInt"]],
            ["retval", "return", ["::SOAP::SOAPBoolean"]] ],
          { :request_style =>  :rpc, :request_use =>  :encoded,
            :response_style => :rpc, :response_use => :encoded,
            :faults => {} }
        ],
        [ XSD::QName.new(NsLmapi, "CreateTopic"),
          "",
          "createTopic",
          [ ["in", "TopicStructIn", ["Postal::Lmapi::TopicStruct", "http://tempuri.org/ns1.xsd", "Postal::Lmapi::TopicStruct"]],
            ["retval", "return", ["::SOAP::SOAPBoolean"]] ],
          { :request_style =>  :rpc, :request_use =>  :encoded,
            :response_style => :rpc, :response_use => :encoded,
            :faults => {} }
        ],
        [ XSD::QName.new(NsLmapi, "UpdateTopic"),
          "",
          "updateTopic",
          [ ["in", "TopicStructIn", ["Postal::Lmapi::TopicStruct", "http://tempuri.org/ns1.xsd", "Postal::Lmapi::TopicStruct"]],
            ["retval", "return", ["::SOAP::SOAPBoolean"]] ],
          { :request_style =>  :rpc, :request_use =>  :encoded,
            :response_style => :rpc, :response_use => :encoded,
            :faults => {} }
        ],
        [ XSD::QName.new(NsLmapi, "DeleteTopic"),
          "",
          "deleteTopic",
          [ ["in", "TopicTitle", ["::SOAP::SOAPString"]],
            ["retval", "return", ["::SOAP::SOAPBoolean"]] ],
          { :request_style =>  :rpc, :request_use =>  :encoded,
            :response_style => :rpc, :response_use => :encoded,
            :faults => {} }
        ],
        [ XSD::QName.new(NsLmapi, "GetPreviewMailing"),
          "",
          "getPreviewMailing",
          [ ["in", "PreviewStructIn", ["Postal::Lmapi::PreviewStruct", "http://tempuri.org/ns1.xsd", "Postal::Lmapi::PreviewStruct"]],
            ["retval", "return", ["::SOAP::SOAPString"]] ],
          { :request_style =>  :rpc, :request_use =>  :encoded,
            :response_style => :rpc, :response_use => :encoded,
            :faults => {} }
        ],
        [ XSD::QName.new(NsLmapi, "CreateServerAdmin"),
          "",
          "createServerAdmin",
          [ ["in", "ServerAdminStructIn", ["Postal::Lmapi::ServerAdminStruct", "http://tempuri.org/ns1.xsd", "Postal::Lmapi::ServerAdminStruct"]],
            ["retval", "return", ["::SOAP::SOAPInt"]] ],
          { :request_style =>  :rpc, :request_use =>  :encoded,
            :response_style => :rpc, :response_use => :encoded,
            :faults => {} }
        ],
        [ XSD::QName.new(NsLmapi, "UpdateServerAdmin"),
          "",
          "updateServerAdmin",
          [ ["in", "ServerAdminStructIn", ["Postal::Lmapi::ServerAdminStruct", "http://tempuri.org/ns1.xsd", "Postal::Lmapi::ServerAdminStruct"]],
            ["retval", "return", ["::SOAP::SOAPBoolean"]] ],
          { :request_style =>  :rpc, :request_use =>  :encoded,
            :response_style => :rpc, :response_use => :encoded,
            :faults => {} }
        ],
        [ XSD::QName.new(NsLmapi, "DeleteServerAdmin"),
          "",
          "deleteServerAdmin",
          [ ["in", "ServerAdminStructIn", ["Postal::Lmapi::ServerAdminStruct", "http://tempuri.org/ns1.xsd", "Postal::Lmapi::ServerAdminStruct"]],
            ["retval", "return", ["::SOAP::SOAPBoolean"]] ],
          { :request_style =>  :rpc, :request_use =>  :encoded,
            :response_style => :rpc, :response_use => :encoded,
            :faults => {} }
        ],
        [ XSD::QName.new(NsLmapi, "CreateSiteAdmin"),
          "",
          "createSiteAdmin",
          [ ["in", "SiteAdminStructIn", ["Postal::Lmapi::SiteAdminStruct", "http://tempuri.org/ns1.xsd", "Postal::Lmapi::SiteAdminStruct"]],
            ["retval", "return", ["::SOAP::SOAPInt"]] ],
          { :request_style =>  :rpc, :request_use =>  :encoded,
            :response_style => :rpc, :response_use => :encoded,
            :faults => {} }
        ],
        [ XSD::QName.new(NsLmapi, "UpdateSiteAdmin"),
          "",
          "updateSiteAdmin",
          [ ["in", "SiteAdminStructIn", ["Postal::Lmapi::SiteAdminStruct", "http://tempuri.org/ns1.xsd", "Postal::Lmapi::SiteAdminStruct"]],
            ["retval", "return", ["::SOAP::SOAPBoolean"]] ],
          { :request_style =>  :rpc, :request_use =>  :encoded,
            :response_style => :rpc, :response_use => :encoded,
            :faults => {} }
        ],
        [ XSD::QName.new(NsLmapi, "DeleteSiteAdmin"),
          "",
          "deleteSiteAdmin",
          [ ["in", "SiteAdminStructIn", ["Postal::Lmapi::SiteAdminStruct", "http://tempuri.org/ns1.xsd", "Postal::Lmapi::SiteAdminStruct"]],
            ["retval", "return", ["::SOAP::SOAPBoolean"]] ],
          { :request_style =>  :rpc, :request_use =>  :encoded,
            :response_style => :rpc, :response_use => :encoded,
            :faults => {} }
        ],
        [ XSD::QName.new(NsLmapi, "CreateContent"),
          "",
          "createContent",
          [ ["in", "ContentStructIn", ["Postal::Lmapi::ContentStruct", "http://tempuri.org/ns1.xsd", "Postal::Lmapi::ContentStruct"]],
            ["retval", "return", ["::SOAP::SOAPInt"]] ],
          { :request_style =>  :rpc, :request_use =>  :encoded,
            :response_style => :rpc, :response_use => :encoded,
            :faults => {} }
        ],
        [ XSD::QName.new(NsLmapi, "UpdateContent"),
          "",
          "updateContent",
          [ ["in", "ContentStructIn", ["Postal::Lmapi::ContentStruct", "http://tempuri.org/ns1.xsd", "Postal::Lmapi::ContentStruct"]],
            ["retval", "return", ["::SOAP::SOAPBoolean"]] ],
          { :request_style =>  :rpc, :request_use =>  :encoded,
            :response_style => :rpc, :response_use => :encoded,
            :faults => {} }
        ],
        [ XSD::QName.new(NsLmapi, "DeleteContent"),
          "",
          "deleteContent",
          [ ["in", "ContentStructIn", ["Postal::Lmapi::ContentStruct", "http://tempuri.org/ns1.xsd", "Postal::Lmapi::ContentStruct"]],
            ["retval", "return", ["::SOAP::SOAPBoolean"]] ],
          { :request_style =>  :rpc, :request_use =>  :encoded,
            :response_style => :rpc, :response_use => :encoded,
            :faults => {} }
        ],
        [ XSD::QName.new(NsLmapi, "SelectListsEx"),
          "",
          "selectListsEx",
          [ ["in", "ListName", ["::SOAP::SOAPString"]],
            ["in", "SiteName", ["::SOAP::SOAPString"]],
            ["in", "FieldsToFetch", ["Postal::Lmapi::ArrayOfstring", "http://www.lyris.com/lmapi", "Postal::Lmapi::ArrayOfstring"]],
            ["in", "WhereClause", ["Postal::Lmapi::ArrayOfstring", "http://www.lyris.com/lmapi", "Postal::Lmapi::ArrayOfstring"]],
            ["retval", "return", ["Postal::Lmapi::ArrayOfArrayOfstring", "http://www.lyris.com/lmapi", "Postal::Lmapi::ArrayOfArrayOfstring"]] ],
          { :request_style =>  :rpc, :request_use =>  :encoded,
            :response_style => :rpc, :response_use => :encoded,
            :faults => {} }
        ],
        [ XSD::QName.new(NsLmapi, "SelectMembersEx"),
          "",
          "selectMembersEx",
          [ ["in", "FieldsToFetch", ["Postal::Lmapi::ArrayOfstring", "http://www.lyris.com/lmapi", "Postal::Lmapi::ArrayOfstring"]],
            ["in", "FilterCriteriaArray", ["Postal::Lmapi::ArrayOfstring", "http://www.lyris.com/lmapi", "Postal::Lmapi::ArrayOfstring"]],
            ["retval", "return", ["Postal::Lmapi::ArrayOfArrayOfstring", "http://www.lyris.com/lmapi", "Postal::Lmapi::ArrayOfArrayOfstring"]] ],
          { :request_style =>  :rpc, :request_use =>  :encoded,
            :response_style => :rpc, :response_use => :encoded,
            :faults => {} }
        ]
      ]

      def initialize(endpoint_url = nil)
        endpoint_url ||= DefaultEndpointUrl
        super(endpoint_url, nil)
        self.mapping_registry = Postal::Lmapi::MappingRegistry::EncodedRegistry
        self.literal_mapping_registry = Postal::Lmapi::MappingRegistry::LiteralRegistry
        init_methods
      end

    private

      def init_methods
        Methods.each do |definitions|
          opt = definitions.last
          if opt[:request_style] == :document
            add_document_operation(*definitions)
          else
            add_rpc_operation(*definitions)
            qname = definitions[0]
            name = definitions[2]
            if qname.name != name and qname.name.capitalize == name.capitalize
              ::SOAP::Mapping.define_singleton_method(self, qname.name) do |*arg|
                __send__(name, *arg)
              end
            end
          end
        end
      end
    end
  end
end
